# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Mavenm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: version change
      run: |
        a=$(cat VERSION)
        echo $a
        b=$(awk -vFS=. -vOFS=. '{$3++;print}' <<<$a)
        sed -i {s/$a/$b/} VERSION
        cat VERSION
        ls -a
        pwd
        git config --global user.email "sharath.kumarjadala@livewire.com"
        git config --global user.name "sharath"
        git add /home/runner/work/java-maven/java-maven/VERSION
        git commit -m "Bumped version"
        git push origin main --force
  
    - name: Create Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: $VERSION
          release_name: Release $VERSION
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
