name: Print environment variable

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: prod
        required: true
jobs:
  build:
 
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
    - uses: actions/checkout@v3
    - name: Set up OPENJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
#This step includes stepup for maven
    - name: generates the build and creates jar file
#This tep Includes we are installing the dependencies from the pom.xml and generates the jar file
      run: mvn clean install --file pom.xml
