name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
   

    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: version change
      run: |
        a=$(cat VERSION)
        echo $a
        b=$(awk -vFS=. -vOFS=. '{$3++;print}' <<<$a)
        sed -i {s/$a/$b/} VERSION
        cat VERSION
        ls -a
        pwd
        git config --global user.email "sharath.kumarjadala@livewire.com"
        git config --global user.name "sharath"
        git add /home/runner/work/java-maven/java-maven/VERSION
        git commit -m "Bumped version"
        git push origin master --force
       
